title: coo11's start page

images:

bookmark:
  - name: Gmail
    url: https://inbox.google.com/
    favicon: gmail.png
  - name: QQé‚®ç®±
    url: https://mail.qq.com
    favicon: qqmail.png
  - name: Outlook
    url: https://go.microsoft.com/fwlink/p/?LinkID=2125442
    # url: https://outlook.live.com/mail/0/inbox
    favicon: outlook.png
  - name: 163é‚®ç®±
    url: https://mail.163.com/
    favicon: netease163.png
  # - name: YandexMail
  #   url: https://mail.yandex.com/
  # - name: Google Earth
  #   url: https://earth.google.com/web/
  # - name: Google Maps
  #   url: https://www.google.com/maps/
  - name: Wikipedia
    url: https://zh.wikipedia.org/zh-hans/Wikipedia:%E9%A6%96%E9%A1%B5
    favicon: wikipedia.png
  - name: Youtube
    url: https://www.youtube.com
    favicon: youtube.png
  - name: å“”å“©å“”å“©
    url: https://t.bilibili.com
    #  url: https://search.bilibili.com/all
    favicon: bilibili.png
  - name: GitHub
    url: https://github.com
    favicon: github.png
    faviconAlt: github_d.png
  - name: Notion
    url: https://www.notion.so/
    favicon: notion.png
    faviconAlt: notion_d.png
  - name: Telegram
    #  url: https://web.telegram.org/k/
    url: https://web.telegram.org/a/
    favicon: telegram.png
  - name: å¾®ä¿¡
    url: https://wx2.qq.com
    favicon: wechat2.png
  - name: DeepL
    url: https://www.deepl.com/translator
    favicon: deepl.png
    faviconAlt: deepl_d.png
  - name: è°·æ­Œç¿»è¯‘
    url: https://translate.google.com/
    favicon: googletranslate.png
  - name: ç™¾åº¦ç¿»è¯‘
    url: https://fanyi.baidu.com/
    favicon: baidutranslate.png

  - category: Shortcuts
  - name: MSNå¤©æ°”
    url: https://www.msn.com/zh-cn/weather/forecast
    favicon: msn.png
  - name: æ–‡ä»¶ä¼ è¾“åŠ©æ‰‹
    url: https://szfilehelper.weixin.qq.com
    favicon: wechat.png
  - name: Rentry.co
    url: https://rentry.co/m5
    favicon: rentryco.png
  - name: Paste.ee
    url: https://paste.ee/
  # - name: Telegraph
  #   url: https://telegra.ph
  # - name: GIR
  #   url: https://coo11.github.io/gir/
  #   favicon: pic.png
  - name: QRCode
    url: https://mazhuren.com
    favicon: qrcode.png
  - name: Netcut
    url: https://netcut.cn/
    favicon: netcut.png
    faviconAlt: netcut_d.png
  - name: <b>More</b>
    newTab: true
    url: https://rentry.co/g1
    favicon: more.png

  - category: SNS
  - name: Twitter
    url: https://x.com/home
    favicon: twitter.png
    faviconAlt: twitter_d.png
  - name: å¾®åš
    url: https://weibo.com
    favicon: sinaweibo.png
  - name: Discord
    url: https://discord.com/channels/@me
    favicon: discord.png
  - name: TikTok
    url: https://www.tiktok.com
    favicon: tiktok.png
    faviconAlt: tiktok_d.png
  - name: å°çº¢ä¹¦
    url: https://www.xiaohongshu.com/explore
    favicon: xiaohongshu.png
  - name: LOFTER
    url: https://www.lofter.com/
    favicon: lofter.png
  - name: Bluesky
    url: https://bsky.app/
    favicon: bluesky.png

  - category: Forum
  - name: NGA
    url: https://bbs.nga.cn
    favicon: nga.png
  - name: V2EX
    url: https://cn.v2ex.com/?tab=all
    favicon: v2ex.png
  - name: reddit
    url: https://www.reddit.com
    favicon: reddit.png
  # - name: 4chan
  #   url: https://www.4chan.org
  # - name: Ğ”Ğ²Ğ°.Ñ‡
  #   url: https://2ch.hk
  - name: Steam
    url: https://store.steampowered.com/
    # url: https://steamcommunity.com
    favicon: steam.png
  - name: PCbeta
    url: http://bbs.pcbeta.com/forum.php
    favicon: pcbeta.png
  - name: Stage1st
    url: https://bbs.saraba1st.com/2b/forum-75-1.html
    # url: https://bbs.saraba1st.com/2b/forum.php
    favicon: stage1st.png
  - name: çŸ¥ä¹
    url: https://www.zhihu.com
    favicon: zhihu.png
  # - name: ExcelHome
  #   url: http://club.excelhome.net/forum.php
  # - name: å¾çˆ±ç ´è§£
  #   url: https://www.52pojie.cn
  - name: Hacker News
    url: https://news.ycombinator.com/
    favicon: hackernews.png
  # - name: çœ‹é›ª
  #   url: https://bbs.kanxue.com/
  - name: èŒ¶é¦†
    url: https://bbs.imoutolove.me/thread.php?fid-9.html
    favicon: soulplus.png

  - category: LLM
  - name: ChatGPT
    url: https://chatgpt.com/?model=auto&temporary-chat=true
    favicon: chatgpt.png
  # - name: é€šä¹‰åƒé—®
  #   url: https://tongyi.aliyun.com/qianwen/
  - name: Qwen
    url: https://chat.qwen.ai/
    favicon: qwen.png
  - name: DeepSeek
    url: https://chat.deepseek.com/
    favicon: deepseek.png
  - name: AI Studio
    url: https://aistudio.google.com/prompts/new_chat
    favicon: google.png
    faviconAlt: google_d.png
  - name: Gemini
    url: https://gemini.google.com/app
  - name: Claude
    url: https://claude.ai/
    favicon: claude.png
  - name: Mistral
    url: https://chat.mistral.ai/
    favicon: mistral.png
  - name: Copilot
    url: https://edgeservices.bing.com/edgesvc/chat?clientscopes=chat,moblike,mobfull
    # url: https://chat.bing.com
    favicon: mscopilot.png
  # - name: æ–‡å¿ƒä¸€è¨€
  #   url: https://yiyan.baidu.com/
  #   favicon: yiyan.png
  # - name: Poe
  #   url: https://poe.com/
  #   favicon: poe.png
  #   faviconAlt: poe_d.png
  - name: LMArena
    url: https://lmarena.ai/?leaderboard
    favicon: gradio.png

  - category: Dev
  - name: StackOverflow
    url: https://stackoverflow.com
    favicon: stackoverflow.png
  - name: Hugging Face
    url: https://huggingface.co/
    favicon: huggingface.png
  # - name: SuperUser
  #   url: https://superuser.com
  # - name: MDN
  #   url: https://developer.mozilla.org/zh-CN/docs/Learn
  - name: RegExr
    url: https://regexr.com
    favicon: regexr.png
  - name: JSFiddle
    url: https://jsfiddle.net
    favicon: jsfiddle.png
    faviconAlt: fofa_d.png
  - name: GitLab
    url: https://gitlab.com
    favicon: gitlab.png
  - name: VSCode
    url: https://vscode.dev/
    favicon: vscode.png
  - name: CanIUse
    url: https://caniuse.com/
  - name: Carbon
    url: https://carbon.now.sh
  - name: Minifier
    url: https://hm.ehhh.eu.org/
    favicon: terser.png
  - name: CyberChef
    url: https://gchq.github.io/CyberChef/
    favicon: cyberchef.png
  - name: JSON Editor
    # url: https://jsoneditoronline.com/
    url: https://t.ehhh.eu.org/jsoneditor/
    favicon: json.png
    faviconAlt: json_d.png
  - name: REQBIN
    url: https://reqbin.com/
    favicon: reqbin.png
  - name: <b>More</b>
    newTab: true
    url: https://rentry.co/idev
    favicon: more.png

  - category: Search
  - name: Google
    url: https://www.google.com/ncr
    favicon: google.png
    faviconAlt: google_d.png
  - name: Bing
    url: https://www.bing.com
    favicon: bing.png
  - name: DuckDuckGo
    url: https://duckduckgo.com/
  - name: WolframAlpha
    url: https://www.wolframalpha.com/
    favicon: wolframalpha.png
  - name: Startpage
    url: https://startpage.com
  - name: Googleå­¦æœ¯
    url: https://scholar.google.com
    favicon: googlescolar.png
  - name: Yandexæœå›¾
    url: https://yandex.com/images/
    favicon: yandeximage.png
  # - name: Google å›¾ç‰‡
  #   url: https://images.google.com
  #   favicon: google.png
  # - name: ç™¾åº¦è¯†å›¾
  #   url: https://image.baidu.com/?fr=shitu
  #   favicon: baidu.png
  - name: SauceNAO
    url: https://saucenao.com
    favicon: saucenao.png
  - name: ASCII2D
    url: https://ascii2d.net
  # - name: IQDB
  #   url: https://iqdb.org/
  # - name: Twitter é«˜çº§æœç´¢
  #   url: https://twitter.com/search-advanced
  #   favicon: twitter.png
  - name: WAIT
    url: https://trace.moe/
  - name: æœå›¾Boté…±
    url: https://soutubot.moe/
  - name: AnimeTrace
    url: https://ai.animedb.cn/

  - category: Utils
  - name: GVoice
    url: https://voice.google.com/messages
    favicon: googlevoice.png
  - name: Inoreader
    url: https://www.inoreader.com/zh-hans/
    favicon: inoreader.png
  - name: SYMBL
    url: https://symbl.cc/cn/unicode-table/
    favicon: symbl.png
    faviconAlt: symbl_d.png
  - name: Dropmail
    url: https://dropmail.me/zh/
    favicon: at.png
  - name: TableConvert
    url: https://tableconvert.com
    favicon: tableconvert.png
  - name: FOFA
    url: https://fofa.info/
    favicon: fofa.png
  - name: IP
    url: https://ip.skk.moe/
    favicon: ip.png
  - name: InternetArchive
    url: https://archive.org/web/
    favicon: internetarchive.png
    faviconAlt: internetarchive_d.png
  - name: Archive.today
    url: https://archive.is
  # - name: Gyotaku
  # - name: ã‚¦ã‚§ãƒ–é­šæ‹“
  - name: é­šæ‹“
    url: https://megalodon.jp/
  - name: r12a
    url: https://r12a.github.io/app-encodings/
  - name: AriaNg
    # Search instances: https://www.google.com/search?q=0.00+B%2Fs+AriaNg
    # url: http://ariang.mayswind.net/latest/#!/settings/rpc/set/http/127.0.0.1/6800/jsonrpc
    # url: http://www.ykamc.cn/#!/settings/rpc/set/http/127.0.0.1/6800/jsonrpc
    # url: http://aria2.iloli.li/#!/settings/rpc/set/http/127.0.0.1/6800/jsonrpc
    url: javascript:(()=%3E%7Bvar%20t=prompt(%22RPC%20Config:%22,%22http/127.0.0.1/6800%22);t&&(location.href=%22http://ariang.mayswind.net/latest/#!/settings/rpc/set/%22+t+%22/jsonrpc%22)%7D)();
    favicon: downarrow.png
  - name: PaperSizes
    url: https://papersizes.io
  # - name: CloudConvert
  #   url: https://cloudconvert.com
  - name: iLovePDF
    url: https://www.ilovepdf.com/zh-cn
    favicon: ilovepdf.png
  - name: HTML2MD
    url: https://www.helloworld.net/html2md
    # url: https://tool.lu/markdown/
    favicon: helloworld.png
  - name: HTML Cleaner
    url: https://html-cleaner.com
  - name: Markdown
    url: https://markdownlivepreview.com/
    favicon: markdown.png
  - name: Speedtest
    url: https://test.ustc.edu.cn/
    # Nanjing University Speed Test
    # url: https://test.nju.edu.cn/
    # ç§»åŠ¨ä¸šåŠ¡é€Ÿç‡æµ‹è¯•å¹³å°
    # url: http://speed.bj.10086.cn:3060/
    # å¹¿ä¸œç”µä¿¡å®½å¸¦æµ‹é€Ÿå¹³å°
    # url: https://10000.gd.cn/#/speed
  - name: Text Compare
    url: https://diffsuite.com/zh/
  - name: <b>Index</b>
  # - name: å¦™å¦™å°å·¥å…·
    newTab: true
    url: https://t.ehhh.eu.org/
    favicon: pokeball.png

  - category: Streaming Media
  - name: Twitch
    url: https://www.twitch.tv
    favicon: twitch.png
  - name: è™ç‰™
    url: https://www.huya.com
    favicon: huya.png
  - name: æ–—é±¼
    url: https://www.douyu.com
    favicon: douyu.png
  - name: Spotify
    url: https://open.spotify.com/
    favicon: spotify.png
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    url: https://music.163.com/#/my/
    favicon: neteasemusic.png
  - name: æŠ–éŸ³ç›´æ’­
    url: https://live.douyin.com/
    favicon: tiktok.png
    faviconAlt: tiktok_d.png

  - category: Consume
  - name: äº¬ä¸œ
    url: https://search.jd.com
    favicon: jingdong.png
  - name: æ·˜å®
    url: https://search.taobao.com
    favicon: taobao.png
  - name: é—²é±¼
    url: https://www.goofish.com/
    favicon: xianyu.png
  # - name: é¥¿äº†ä¹ˆ
  #   url: https://h5.ele.me
  #   favicon: eleme.png
  # - name: ç¾å›¢
  #   url: https://h5.waimai.meituan.com/waimai/mindex/home
  #   favicon: meituanwaimai.png
  - name: 1688
    url: https://search.1688.com
    favicon: alibaba.png
  - name: å”¯å“ä¼š
    url: https://www.vip.com/
    favicon: vipcom.png
  - name: Amazon
    url: https://www.amazon.co.jp
    favicon: amazon.png
  - name: ä»€ä¹ˆå€¼å¾—ä¹°
    url: https://www.smzdm.com
    favicon: smzdm.png

  - category: Image
  - name: PixFix
    url: https://zh.pixfix.com
    favicon: pixfix.png
  - name: waifu2x
    url: https://www.waifu2x.net/index.zh-CN.html
  # - name: TinyPNG
  # url: https://tinypng.com
  - name: PhotoFun
    url: https://www.photofun.cn/compress/
  - name: Watermark
    url: https://watermark.yycc.dev/ # https://github.com/funnyzak/watermark
  - name: EZGIF
    url: https://ezgif.com
  # - name: ImgOps
  #   url: https://imgops.com
  - name: PSDTool
    url: https://oov.github.io/psdtool/
    favicon: github.png
    faviconAlt: github_d.png
  - name: SvgPathEditor
    url: https://yqnn.github.io/svg-path-editor/
  - name: BoxySVG
    url: https://boxy-svg.com/app
    favicon: boxsvg.png
  - name: Unsplash
    url: https://unsplash.com/
    favicon: unsplash.png
    faviconAlt: unsplash_d.png

  - category: Cloud Service
  - name: åšæœäº‘
    url: https://www.jianguoyun.com
    favicon: jianguoyun.png
  - name: iCloud
    url: https://www.icloud.com/
    favicon: icloud.png
  - name: MEGA
    url: https://mega.nz/fm/
    favicon: mega.png
  - name: Wokers
    url: https://workers.cloudflare.com/playground
    # url: https://dash.cloudflare.com/?account=workers
    favicon: workers.png
  - name: Apps Script
    url: https://script.google.com/home
    favicon: appsscript.png
  - name: GDrive
    url: https://drive.google.com/drive/my-drive
    favicon: gdrive.png
  - name: OneDrive
    url: https://onedrive.live.com
    favicon: onedrive.png
  - name: Colab
    url: https://colab.research.google.com/notebooks/empty.ipynb
    favicon: colab.png
  - name: Vercel
    url: https://vercel.com/dashboard
    favicon: vercel.png
    faviconAlt: vercel_d.png
  - name: ç™¾åº¦ç½‘ç›˜
    url: https://pan.baidu.com/disk/home
    favicon: baidunetdisk.png
  - name: é˜¿é‡Œäº‘ç›˜
    url: https://www.alipan.com/drive/file/all
    favicon: aliyundrive.png
  - name: PikPak
    url: https://mypikpak.com/drive/all
    favicon: pikpak.png
  - name: è“å¥äº‘
    url: https://up.woozooo.com/

  - category: ACG
  - name: Danbooru
    url: https://danbooru.donmai.us/
    favicon: danbooru.png
  # - name: Gelbooru
  #   url: https://gelbooru.com/index.php?page=post&s=list&tags=user:danbooru
  #   favicon: gelbooru.png
  - name: yande.re
    url: https://yande.re/post
    favicon: yandere.png
  - name: Kemono
    url: https://kemono.party/artists
    favicon: kemono.png
  # - name: Sankaku
  #   url: https://sankaku.app/zh-CN
  # - name: Konachan
  #   url: https://konachan.com/post
  #   favicon: konachan.png
  - name: ç•ªç»„è®¡åˆ’
    url: https://bgm.tv/group/boring/forum # é è°±äººç”ŸèŒ¶è¯ä¼š
    # url: https://bgm.tv/group/a/forum # ï½æŠ€æœ¯å®…çœŸå¯æ€•ï½
  # - name: AcFun
  #   url: https://www.acfun.cn
  #   favicon: acfun.png
  # - name: çˆ±æ‹åŠ¨æ¼«
  #   url: https://www.kisssub.org/
  - name: Pixiv
    url: https://www.pixiv.net/bookmark_new_illust.php
    favicon: pixiv.png
  - name: å¤©ä½¿åŠ¨æ¼«
    url: https://www.tsdm39.com/forum.php
    favicon: tsdm.png
  - name: èŒå¨˜ç™¾ç§‘
    url: https://zh.moegirl.org.cn/Mainpage
    favicon: moegirl.png
    faviconAlt: moegirl_d.png
  - name: å‹•æ¼«èŠ±åœ’
    url: https://share.dmhy.org
  # - name: æ¨±èŠ±åŠ¨æ¼«
  #   url: https://www.yinhuadm.one/
  #   favicon: cherryblossom.png
  # - name: Sukebei
  #   url: https://sukebei.nyaa.si/
  #   favicon: nyaa.png
  - name: Nyaa
    url: https://nyaa.si/
    favicon: nyaa.png
  - name: <b>More</b>
    newTab: true
    url: https://rentry.co/acg
    favicon: more.png

  - category: Calc
  - name: NumberEmpire
    url: https://zh.numberempire.com/
  - name: MathStudio
    url: http://mathstud.io
    favicon: mathstudio.png
  - name: Desmos
    url: https://www.desmos.com/calculator?lang=zh-CN
    favicon: desmos.png
    # Alternative
    # https://www.geogebra.org/graphing
  - name: Mathway
    url: https://www.mathway.com/zh/Algebra
    favicon: mathway.png

  - category: Life
  # - name: é»˜æ²™ä¸œè¯Šç–—æ‰‹å†Œ
  - name: é»˜æ°æ‰‹å†Œ
    url: https://www.msdmanuals.cn/home
    favicon: merck.png
  - name: å°æ—¶ç™¾ç§‘
    url: https://wuli.wiki/online/index.html
    favicon: wuliwiki.png
  - name: 12306
    url: https://www.12306.cn/index/
    favicon: railway12306.png
  # - name: å¤©æ°”ç½‘
  #   url: http://www.weather.com.cn/
  #   favicon: cnweather.png
  - name: å¤©çœ¼æŸ¥
    url: https://www.tianyancha.com
    favicon: tianyancha.png
  - name: ä¼æŸ¥æŸ¥
    url: https://www.qcc.com
    favicon: qichacha.png
  - name: å†å²ä»·æ ¼æŸ¥è¯¢
    url: https://www.lsjgcx.com


  - category: Unclassified
  - name: Applist
    newTab: true
    url: https://rentry.co/applist
    favicon: rentryco.png
  - name: NoUse
    newTab: true
    url: https://rentry.co/u6
  - name: LGUG
    newTab: true
    url: https://rentry.co/lgug
    favicon: rentryco.png
  - name: Githubâœ‹â­
    url: https://rentry.co/githubnostar
    favicon: github.png
  - name: IMDb
    url: https://www.imdb.com
  - name: SteamDB
    url: https://steamdb.info
    favicon: steamdb.png
    faviconAlt: steamdb_d.png
  - name: MusicBrainZ
    url: https://musicbrainz.org/search
    favicon: musicbrainz.png
  - name: ç¦åˆ©å§
    url: https://fuliba.net
  - name: musicForProgramming
    url: https://musicforprogramming.net
  - name: Noises.online
    url: https://noises.online
  - name: AHA Music
    url: https://www.aha-music.com/upload

  # - category: NSFW
  # - name: E-Hentai
  #   url: https://e-hentai.org/
  # - name: ExHentai
  #   url: https://exhentai.org/
  # - name: ç»…å£«ä»“åº“
  #   url: https://galacg.github.io/
  # - name: ç‰ç’ƒç¥ç¤¾â›©
  #   url: https://acg.gy/
  # - name: ç´³å£«ã®åº­ğŸ©
  #   url: https://gmgard.com/
  # - name: HVDB
  #   url: https://hvdb.me/Dashboard/
  # - name: ï¼­ï¼¡ï¼®ï¼§ï¼¡ï¼ï¼¤ï¼¢
  #   url: https://adultcomic.dbsearch.net/
  # - name: ğŸ¼Panda Backup
  #   url: https://panda.chaika.moe/
  # - name: è‰æ¦´ç¤¾åŒº
  #   url: https://t66y.com/index.php
  #   favicon: caoliu.png
  # - name: PornDude
  #   url: https://theporndude.com/zh
  #   favicon: porndude.png
